# Site settings
title: chaospott - wir sind da wat am hacken dran...
email: info@chaospott.de
description: >
  Wir sind der örtliche Erfa-Kreis des Chaos Computer Clubs in Essen. Unsere Gesprächsthemen und Projekte reichen von Soft- und Hardware zu Datenschutz und Netzpolitik. 
  Alle Interessierten sind herzlich zu unserem Treff eingeladen.
baseurl: ""
url: "https://chaospott.de"
# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
paginate: 5
paginate_path: "/blog/:num"
plugins: [jekyll-paginate]
include: [
  ".well-known"
]
